version: '3'
services:
    rabbit:
        hostname: rabbit
        image: rabbitmq:3-management
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=mypass
        ports:
            - "5672:5672"
            - "15672:15672"
    worker_1:
        build:
            context: celery-queue
            dockerfile: dockerfile
        depends_on:
            - rabbit
    worker_2:
        build:
            context: celery-queue
            dockerfile: dockerfile
        depends_on:
            - rabbit
    server:
        container_name: flask-celery
        build:
            context: ./api
            dockerfile: dockerfile
        ports:
            - '5000:5000'
        restart: always
        environment:
            ENV: DEVELOPMENT
        depends_on:
            - rabbit
    flower:
        image: mher/flower
        environment:
            - CELERY_BROKER_URL=amqp://admin:mypass@rabbit
            - FLOWER_PORT=5555
        ports:
            - 5555:5555
        depends_on:
            - rabbit